on:
  push:
  pull_request:
  workflow_dispatch:

name: Test SFTP Upload Files

jobs:
  upload_files:
    runs-on: ubuntu-latest
    env:
      SF_ANDREMIKULEC_PWD: ${{ secrets.SF_ANDREMIKULEC_PWD }}
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: 'frs.sourceforge.net'
        port: 22
        username: 'andremikulec,andremikulec.u'
        password: '${{ env.SF_ANDREMIKULEC_PWD }}'
        localPath: './readme_Test_SFTP_Upload_Files.md'
        remotePath: '/home/frs/project/andremikulec'
