on:
  push:
  pull_request:
  workflow_dispatch:

name: Test read a secret

# EXAMPLE
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

jobs:
  my-jobname:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
    steps:
      - if: ${{ env.SUPER_SECRET != '' }}
        run: echo 'This step will only run if the secret has a value set.'
      - if: ${{ env.SUPER_SECRET == '' }}
        run: echo 'This step will only run if the secret does not have a value set.'
