on:
  push:
  pull_request:
  workflow_dispatch:

name: Test SFTP Deploy Files

jobs:
  deploy_files:
    runs-on: ubuntu-latest
    env:
      SF_ANDREMIKULEC_PWD: ${{ secrets.SF_ANDREMIKULEC_PWD }}
    name: Deploy a builded file.
    steps:
    - if: ${{ env.SF_ANDREMIKULEC_PWD != '' }}
      run: echo 'This step will only run if the secret has a value set.'
    - if: ${{ env.SF_ANDREMIKULEC_PWD == '' }}
      run: echo 'This step will only run if the secret does not have a value set.'
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Deploy Files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'andremikulec,andremikulec.u'
        server: 'frs.sourceforge.net'
        port: 22
        local_path: './readme_Test_SFTP_Deploy_Files.md'
        remote_path: '/home/frs/project/andremikulec'
        sftp_only: true
        password: ${{ env.SF_ANDREMIKULEC_PWD }}
  
